server:
  port: 8081
spring-doc:
  pathsToMatch: /api/**
  title: School Admin API
  version: v1
  description: Management of student and teacher data
  url: http://www.norulshahlam.com/
  name: Shah & Co
  email: norulshahlam@gmail.com
  license-name: License 30AP
  license-url: url
spring:
  application:
    name: school-admin-api
    description: management of student and teacher data
  profiles:
    active: dev