openapi:
  project-title: School Admin API
  project-version: v1
  project-description: Management of student and teacher data
spring-doc:
  pathsToMatch: /api/**
spring:
  application:
    name: assignment-school-admin-api
    description: management of student and teacher data
  profiles:
    active: dev